- name: Find *.sql files in /tmp
  find:
      paths: "/tmp" 
      patterns: "*.sql" 
  register: files_to_delete

- name: Remove the files
  file:
      path: "{{ item.path }}"
      state: absent
  with_items: "{{ files_to_delete.files }}"

