- name: Create Application Dir
  file: 
    path: "{{ application_dir }}"
    state: absent

- name: Copy config
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-enabled
  notify: restart_apache
